const actions = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  SET_INGREDIENTS: 'SET_INGREDIENTS',
  FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
  PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
  PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
  PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
};

export default actions;
